CREATE TABLE notification
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    notifier BIGINT NOT NULL,
    receiver BIGINT NOT NULL,
    outerId BIGINT NOT NULL,
    type INT NOT NULL,
    gmt_create BIGINT NOT NULL,
    status INT DEFAULT 0 NOT NULL
);
COMMENT ON COLUMN NOTIFICATION.NOTIFIER IS '要通知的人';
COMMENT ON COLUMN NOTIFICATION.RECEIVER IS '被评论或回复的人';
COMMENT ON COLUMN NOTIFICATION.OUTERID IS '评论id或问题id';
